# Configs for therealskv.github.io

title: "The Answer is 42"
name: "therealskv.github.io"
email: sathish.velayudam@gmail.com
url: "https://therealskv.github.io"
repository: "therealskv/therealskv.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
  
# settings for author profile
author:
  name   : "Sathish Velayudam"
  avatar : "/assets/images/Photo.jpg"
  bio    : "All things technology"
  location: "Atlanta, GA"
  github : therealskv
  linkedin: sathishvelayudam
  email  : sathish.velayudam@gmail.com


# # comments by disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "therealskv-git"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-116208936-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
